Repository TheClimeet/climeet-android, pull requests merged in 2024-01, with the labels that each got.

#1 [Intro/CMA-26] 스플래시-로그인 구현 (API 연결 전)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/app/App.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/LoginFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/admin/AdminLoginFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/admin/AdminLoginViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/climer/ClimerLoginFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/climer/ClimerLoginViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/onboard/OnBoardAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/onboard/OnBoardFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/SetCragNameFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/ClimerSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/SetClimerNickFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/indicator_anim.xml
  app/src/main/res/anim/top_swipe.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_kakao_login.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_naver_login.xml
  app/src/main/res/drawable/ic_people.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/ic_text_error.xml
  app/src/main/res/drawable/ic_text_logo.xml
  app/src/main/res/drawable/oval_indicator_select.xml
  app/src/main/res/drawable/oval_indicator_unselect.xml
  app/src/main/res/drawable/rect_grey1fill_nostroke_20radius.xml
  app/src/main/res/drawable/rect_mainfill_nostroke_15radius.xml
  app/src/main/res/drawable/rect_mainfill_nostroke_20radius.xml
  app/src/main/res/drawable/test.jpg
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_admin_login.xml
  app/src/main/res/layout/fragment_climer_login.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_onboard.xml
  app/src/main/res/layout/fragment_set_climer_nick.xml
  app/src/main/res/layout/fragment_set_crag_name.xml
  app/src/main/res/layout/item_onboard.xml
  app/src/main/res/navigation/intro_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/text_style.xml
  app/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: feat, fix, chore

#8 [Intro/CMA-41] 전역 리팩토링
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/background/SetAdminBackgroundFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/background/SetAdminBackgroundViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/submitdoc/BusinessRegistrationFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/SetClimerProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/SetClimerProfileViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/adapter/FollowCragRVAdapter.kt
  app/src/main/res/drawable/ic_next_activated.xml
  app/src/main/res/drawable/ic_next_disabled.xml
  app/src/main/res/drawable/ic_next_off.xml
  app/src/main/res/drawable/ic_next_on.xml
  app/src/main/res/drawable/ic_select.xml
  app/src/main/res/drawable/ic_skip.xml
  app/src/main/res/drawable/ic_unselect.xml
  app/src/main/res/drawable/shape_search_box.xml
  app/src/main/res/layout/fragment_announce_admin_signup.xml
  app/src/main/res/layout/fragment_business_registration.xml
  app/src/main/res/layout/fragment_follow_crag.xml
  app/src/main/res/layout/fragment_set_admin_background.xml
  app/src/main/res/layout/fragment_set_admin_id_pw.xml
  app/src/main/res/layout/fragment_set_admin_personal_info.xml
  app/src/main/res/layout/fragment_set_admin_service.xml
  app/src/main/res/layout/fragment_set_climer_level.xml
  app/src/main/res/layout/fragment_set_climer_nick.xml
  app/src/main/res/layout/fragment_set_climer_profile.xml
  app/src/main/res/layout/item_follow_crags.xml
Labels: fix, refactor

#9 [Intro/CMA-27] 사용자 회원가입 (암장 팔로우 ~ 회원가입 완료) UI 수정 및 기능 보완
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/ClimerSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/climbinggoal/ClimbingGoalFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/CompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/FollowCragFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/adapter/FollowCragRVAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/howtoknow/HowToKnowFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/howtoknow/HowToKnowViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/howtoknow/WayAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/model/WayItem.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/noticesetting/NoticeSettingFragment.kt
  app/src/main/java/com/climus/climeet/presentation/util/Constants.kt
  app/src/main/res/drawable/oval_grey7fill_nostroke_noradius.xml
  app/src/main/res/drawable/oval_lightgreyfill_nostroke_noradius.xml
  app/src/main/res/drawable/oval_mainfill_nostroke_noradius.xml
  app/src/main/res/drawable/shape_light_gray_circle.xml
  app/src/main/res/layout/activity_notice_setting.xml
  app/src/main/res/layout/fragment_climbing_goal.xml
  app/src/main/res/layout/fragment_complete.xml
  app/src/main/res/layout/fragment_follow_crag.xml
  app/src/main/res/layout/fragment_how_to_know.xml
  app/src/main/res/layout/fragment_notice_setting.xml
  app/src/main/res/layout/item_follow_crags.xml
  app/src/main/res/layout/item_way.xml
  app/src/main/res/navigation/intro_nav.xml
Labels: feat, style

#10 [Intro/CMA-28] 관리자 회원가입 (ID/PW설정 ~ 완료화면) UI 수정 및 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/alarm/SetAdminAlarmFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/complete/SetAdminCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/idpw/SetAdminIdPwFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/idpw/SetAdminIdPwViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/model/ServiceUiData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/personal/SetAdminPersonalInfoFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/personal/SetAdminPersonalViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/Service.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/ServiceRVAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/SetAdminServiceFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/SetAdminServiceViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/setname/SetCragNameViewModel.kt
  app/src/main/res/drawable/ic_check_anim.xml
  app/src/main/res/layout/fragment_set_admin_alarm.xml
  app/src/main/res/layout/fragment_set_admin_complete.xml
  app/src/main/res/layout/fragment_set_admin_id_pw.xml
  app/src/main/res/layout/fragment_set_admin_personal_info.xml
  app/src/main/res/layout/fragment_set_admin_service.xml
Labels: feat, fix, refactor

#13 [Intro/CMA-27] 사용자 회원가입 암장 팔로우 검색 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/FollowCragFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/FollowCragViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/adapter/FollowCragRVAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/howtoknow/HowToKnowFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/model/FollowCrag.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/noticesetting/NoticeSettingFragment.kt
  app/src/main/res/layout/fragment_follow_crag.xml
  app/src/main/res/layout/item_follow_crags.xml
Labels: feat, fix

#14 [Intro/CMA-27] 유저 회원가입(애니메이션) 리팩토링
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/CompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/SetClimerCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/SetClimerCompleteViewModel.kt
  app/src/main/res/layout/fragment_complete.xml
  app/src/main/res/layout/fragment_how_to_know.xml
  app/src/main/res/layout/fragment_set_climer_complete.xml
  app/src/main/res/navigation/intro_nav.xml
Labels: refactor, style

#12 [Intro/CMA-28] 관리자 회원가입 (안내페이지 ~ 사업자등록증) 리팩토링, IntroActivity 리팩토링
  app/src/main/java/com/climus/climeet/presentation/base/BaseActivity.kt
  app/src/main/java/com/climus/climeet/presentation/customview/PermissionDialog.kt
  app/src/main/java/com/climus/climeet/presentation/customview/PermissionSnackBar.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/error/SetCragErrorFragment.kt
  app/src/main/res/drawable/rect_whitefill_nostroke_12radius.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/dialog_permission.xml
  app/src/main/res/layout/dialog_permission_snackbar.xml
Labels: feat, refactor, style

#15 [Intro/CMA-41] 전역 리팩토링, MainActivity 초기 Setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/presentation/base/BaseActivity.kt
  app/src/main/java/com/climus/climeet/presentation/customview/PermissionDialog.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/alarm/SetAdminAlarmFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/complete/SetAdminCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/error/SetCragErrorCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/SetClimerCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/FollowCragFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/noticesetting/NoticeSettingFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/RecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/upload/UploadFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/climus/climeet/presentation/util/Constants.kt
  app/src/main/res/color/selector_bnv_text.xml
  app/src/main/res/drawable/ic_home_off.xml
  app/src/main/res/drawable/ic_home_on.xml
  app/src/main/res/drawable/ic_mypage_off.xml
  app/src/main/res/drawable/ic_mypage_on.xml
  app/src/main/res/drawable/ic_record_off.png
  app/src/main/res/drawable/ic_record_on.png
  app/src/main/res/drawable/ic_shorts_off.xml
  app/src/main/res/drawable/ic_shorts_on.xml
  app/src/main/res/drawable/ic_upload_off.xml
  app/src/main/res/drawable/ic_upload_on.xml
  app/src/main/res/drawable/selector_menu_home.xml
  app/src/main/res/drawable/selector_menu_mypage.xml
  app/src/main/res/drawable/selector_menu_record.xml
  app/src/main/res/drawable/selector_menu_shorts.xml
  app/src/main/res/drawable/selector_menu_upload.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_notice_setting.xml
  app/src/main/res/layout/dialog_permission.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_set_climer_complete.xml
  app/src/main/res/layout/fragment_set_crag_error_complete.xml
  app/src/main/res/layout/fragment_shorts.xml
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/navigation/intro_nav.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat, fix, refactor

#16 [Intro/CMA-27] 유저 회원가입 API 연결 구현
  app/src/main/java/com/climus/climeet/app/di/ApiModule.kt
  app/src/main/java/com/climus/climeet/app/di/NetworkModule.kt
  app/src/main/java/com/climus/climeet/app/di/RepositoryModule.kt
  app/src/main/java/com/climus/climeet/data/model/request/ClimerSignupRequest.kt
  app/src/main/java/com/climus/climeet/data/model/response/ClimerSignupResponse.kt
  app/src/main/java/com/climus/climeet/data/model/response/UploadImgResponse.kt
  app/src/main/java/com/climus/climeet/data/remote/GlobalApi.kt
  app/src/main/java/com/climus/climeet/data/remote/IntroApi.kt
  app/src/main/java/com/climus/climeet/data/repository/GlobalRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/GlobalRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/data/repository/IntroRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/LoginFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/ClimerSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/SetClimerCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/complete/SetClimerCompleteViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/noticesetting/NoticeSettingFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/setnick/SetClimerNickFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/setprofile/SetClimerProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/setprofile/SetClimerProfileViewModel.kt
  app/src/main/res/drawable/rect_grey3fill_nostroke_8radius.xml
  app/src/main/res/layout/fragment_admin_login.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_notice_setting.xml
  app/src/main/res/layout/fragment_set_climer_complete.xml
Labels: feat, fix, style

#17 [Intro/CMA-28] 관리자 회원가입 아이디 중복확인 버튼 생성, 서비스 및 알림 설정 코드 수정
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/alarm/SetAdminAlarmFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/idpw/SetAdminIdPwViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/SetAdminServiceFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/service/SetAdminServiceViewModel.kt
  app/src/main/res/layout/fragment_set_admin_alarm.xml
  app/src/main/res/layout/fragment_set_admin_complete.xml
  app/src/main/res/layout/fragment_set_admin_id_pw.xml
  app/src/main/res/values/strings.xml
Labels: feat, fix, style

#19 [Intro/CMA-27] 닉네임 중복확인 API 연결, 닉네임 설정 리팩토링
  app/src/main/java/com/climus/climeet/data/remote/IntroApi.kt
  app/src/main/java/com/climus/climeet/data/repository/IntroRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/climer/ClimerLoginViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/setnick/SetClimerNickFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/setnick/SetClimerNickViewModel.kt
  app/src/main/res/layout/fragment_set_climer_nick.xml
Labels: feat, refactor

#20 [Intro/CMA-41] Intro API 수정, BearerInterceptor 구현
  app/src/main/java/com/climus/climeet/app/di/NetworkModule.kt
  app/src/main/java/com/climus/climeet/config/BearerInterceptor.kt
  app/src/main/java/com/climus/climeet/data/model/request/ManagerSignUpRequest.kt
  app/src/main/java/com/climus/climeet/data/model/response/RefreshTokenResponse.kt
  app/src/main/java/com/climus/climeet/data/model/response/SearchAvailableGymResponse.kt
  app/src/main/java/com/climus/climeet/data/model/response/SearchGymResponse.kt
  app/src/main/java/com/climus/climeet/data/remote/IntroApi.kt
  app/src/main/java/com/climus/climeet/data/remote/MainApi.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminAuthMapper.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/AdminSignupForm.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/admin/searchname/SearchCragNameViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/ClimerAuthMapper.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/FollowCragViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/signup/climer/followcrag/adapter/FollowCragRVAdapter.kt
Labels: feat, fix, refactor
