Repository TheClimeet/climeet-android, pull requests merged in 2024-02, with the labels that each got.

#25 [Record/CMA-60] 타이머 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/app/di/DatabaseModule.kt
  app/src/main/java/com/climus/climeet/app/di/RepositoryModule.kt
  app/src/main/java/com/climus/climeet/presentation/customview/NoticePopup.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/RecordCragData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingDatabase.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingRecordDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingRecordRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingRecordRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/DataListConverters.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordViewmodel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/ClimbingCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerService.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectBottomSheetFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectBottomSheetViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectRVAdapter.kt
  app/src/main/res/anim/indicator_anim_timer.xml
  app/src/main/res/drawable/ic_back_grey9.xml
  app/src/main/res/drawable/ic_gray_x.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_record_notice.xml
  app/src/main/res/drawable/ic_record_pause.xml
  app/src/main/res/drawable/ic_record_start.xml
  app/src/main/res/drawable/ic_record_stop.xml
  app/src/main/res/drawable/ic_search2.xml
  app/src/main/res/drawable/oval_whitefill_nostroke_noradius.xml
  app/src/main/res/drawable/rect_grey8fill_nostroke_5radius.xml
  app/src/main/res/drawable/rect_grey9fill_nostroke_20radius.xml
  app/src/main/res/drawable/rect_whitefill_nostroke_10radius.xml
  app/src/main/res/layout/dialog_notice_record.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/layout/fragment_timer_complete.xml
  app/src/main/res/layout/fragment_timer_record.xml
  app/src/main/res/layout/fragment_timer_select_crag_bottom_sheet.xml
  app/src/main/res/layout/fragment_timer_view_pager.xml
  app/src/main/res/layout/item_crag_search_timer.xml
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_style.xml
Labels: feat, refactor, style

#30 [Record/CMA-61] 루트기록, 평균완등률 레이아웃 및 room DB 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/climus/climeet/app/di/DatabaseModule.kt
  app/src/main/java/com/climus/climeet/app/di/RepositoryModule.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/LevelItemForAvg.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/RecordLevelData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/RecordWallData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorImageAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorLevelAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorNameAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/ClimbingRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/DataListConverters.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/data/StopwatchStatesRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/ClimbingDatabase.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/RecordAvgAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectBottomSheetFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectBottomSheetViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectRVAdapter.kt
  app/src/main/res/drawable/record_progrssbar_custom.xml
  app/src/main/res/drawable/rect_grey9fill_nostroke_top20radius.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/layout/fragment_timer_record.xml
  app/src/main/res/layout/fragment_timer_record_root.xml
  app/src/main/res/layout/fragment_timer_select_crag_bottom_sheet.xml
  app/src/main/res/layout/fragment_timer_view_pager.xml
  app/src/main/res/layout/item_crag_search_timer.xml
  app/src/main/res/layout/item_timer_avg_complete.xml
  app/src/main/res/layout/item_timer_route_record.xml
  app/src/main/res/layout/item_timer_sector_image.xml
  app/src/main/res/layout/item_timer_sector_level.xml
  app/src/main/res/layout/item_timer_sector_name.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat, fix, docs

#31 [Shorts/CMA-79] 숏츠 업로드 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/data/remote/MainApi.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/bindingadapters/TextViewBindingAdapters.kt
  app/src/main/java/com/climus/climeet/presentation/ui/DataExtensions.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/IntroViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/intro/login/climer/ClimerLoginFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/selectsector/SelectSectorBottomSheetViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/selectsector/model/SelectedFilter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/upload/UploadFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/upload/UploadViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/upload/complete/UploadCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/util/Constants.kt
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/layout/fragment_upload_complete.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat, fix

#32 [Shorts/CMA-78] 동영상 플레이어 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/presentation/customview/RouteView.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/selectsector/adapter/RouteImageAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/adapter/RouteAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorImageAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsMapper.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/adapter/ShortsDetailAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/detail/ShortsDetailFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsDetailFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsPlayerFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/route/RouteShortsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/upload/complete/UploadCompleteFragment.kt
  app/src/main/res/drawable/ic_bookmark_off.xml
  app/src/main/res/drawable/ic_bookmark_on.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_favorite_off.xml
  app/src/main/res/drawable/ic_favorite_on.xml
  app/src/main/res/drawable/ic_location_small.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_walking.xml
  app/src/main/res/drawable/rect_backgroundfill_nostroke_20radius.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/custom_route_view.xml
  app/src/main/res/layout/fragment_route_shorts.xml
  app/src/main/res/layout/fragment_select_sector_bottom_sheet.xml
  app/src/main/res/layout/fragment_shorts_detail.xml
  app/src/main/res/layout/fragment_shorts_player.xml
  app/src/main/res/layout/item_route_image.xml
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/values/attrs.xml
Labels: feat, fix

#35 [Record/CMA-58] 캘린더 커스텀 구현
  app/src/main/java/com/climus/climeet/app/di/NotificationModule.kt
  app/src/main/java/com/climus/climeet/config/AccessTokenInterceptor.kt
  app/src/main/java/com/climus/climeet/config/BearerInterceptor.kt
  app/src/main/java/com/climus/climeet/data/model/request/CreateTimerClimbingRecordRequest.kt
  app/src/main/java/com/climus/climeet/data/model/response/GetSelectDateRecordResponse.kt
  app/src/main/java/com/climus/climeet/data/remote/MainApi.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/bindingadapters/ImageViewBindingAdapters.kt
  app/src/main/java/com/climus/climeet/presentation/customview/DeleteDialog.kt
  app/src/main/java/com/climus/climeet/presentation/customview/selectdate/SelectDateBottomSheet.kt
  app/src/main/java/com/climus/climeet/presentation/customview/selectdate/SelectDateBottomSheetViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/NavigationExtensions.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/selectsector/model/RouteUiData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/adapter/RouteRecordAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/bottomsheet/selectdate/SelectDateBottomSheetFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/CalendarAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/CalendarFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/CalendarViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/ClimbingRecordCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/CreateClimbingRecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/CreateClimbingRecordViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/CreateRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/RouteRecordUiData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/util/Constants.kt
  app/src/main/res/drawable/ic_check_grey.xml
  app/src/main/res/drawable/ic_check_main.xml
  app/src/main/res/layout/dialog_delete.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_climbing_record_complete.xml
  app/src/main/res/layout/fragment_create_climbing_record.xml
  app/src/main/res/layout/fragment_select_date_bottom_sheet.xml
  app/src/main/res/layout/item_record.xml
  app/src/main/res/layout/item_route_record.xml
  app/src/main/res/layout/item_timer_route_record.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat, fix, refactor

#38 [Record-CMA-61] 스톱워치 운동기록 기록 API 연결 및 데이터 저장
  app/src/main/java/com/climus/climeet/app/di/DatabaseModule.kt
  app/src/main/java/com/climus/climeet/config/AccessTokenInterceptor.kt
  app/src/main/java/com/climus/climeet/data/model/request/CreateTimerClimbingRecordRequest.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/GlobalMapper.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/selectsector/model/RouteUiData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/RecordCragData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/TimerMainViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorImageAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorLevelAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/adapter/RecordSectorNameAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/ClimbingDatabase.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/climbingData/ClimbingRecordRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordDao.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordRepository.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/roomDB/routeRecordData/RouteRecordRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/ClimbingRecordAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/RecordAverageAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/setrecord/SetTimerClimbingRecordViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerService.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/TimerViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectBottomSheetFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/timer/stopwatch/selectcrag/TimerCragSelectRVAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/util/Constants.kt
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/layout/fragment_timer_record.xml
  app/src/main/res/layout/item_timer_route_record.xml
Labels: feat, fix, style

#40 [Global/CMA-41] 마이페이지 셋팅
  app/src/main/java/com/climus/climeet/presentation/ui/NavigationExtensions.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/climerprofile/ClimerProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/GymProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/account/MyPageAccountFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/alarm/MyPageAlarmFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/announce/MyPageAnnounceFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/cheerup/MyPageCheerUpFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/follow/MyPageFollowFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/myprofile/admin/MyPageAdminMyProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/myprofile/climer/MyPageClimerMyProfileFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/myshorts/MyPageMyShortsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/policy/MyPagePolicyFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/mypage/sendopinion/MyPageSendOpinionFragment.kt
  app/src/main/res/layout/fragment_climer_profile.xml
  app/src/main/res/layout/fragment_gym_profile.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_account.xml
  app/src/main/res/layout/fragment_mypage_admin_myprofile.xml
  app/src/main/res/layout/fragment_mypage_alarm.xml
  app/src/main/res/layout/fragment_mypage_announce.xml
  app/src/main/res/layout/fragment_mypage_cheerup.xml
  app/src/main/res/layout/fragment_mypage_climer_myprofile.xml
  app/src/main/res/layout/fragment_mypage_follow.xml
  app/src/main/res/layout/fragment_mypage_myshorts.xml
  app/src/main/res/layout/fragment_mypage_policy.xml
  app/src/main/res/layout/fragment_mypage_sendopinion.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat

#43 [Shorts/CMA-78] 숏츠 메인 에러픽스
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/climus/climeet/app/App.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/ShortsMapper.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/adapter/ShortsCommentAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/adapter/ShortsDetailListener.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/adapter/UpdatedFollowAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/bottomsheet/ShortsCommentBottomSheetFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/bottomsheet/ShortsCommentBottomSheetViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/model/ShortsCommentUiData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsDetailFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsDetailViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsPlayerFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/shorts/player/ShortsPlayerViewModel.kt
  app/src/main/java/com/climus/climeet/service/MyFirebaseMessagingService.kt
  app/src/main/res/layout/fragment_shorts_comment_bottom_sheet.xml
  app/src/main/res/layout/item_add_follow.xml
  app/src/main/res/layout/item_main_comment.xml
  app/src/main/res/layout/item_sub_comment.xml
  app/src/main/res/layout/item_updated_follow.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat, refactor

#44 [Record/CMA-118] 통계 작업 구현
  app/src/main/java/com/climus/climeet/app/App.kt
  app/src/main/java/com/climus/climeet/data/model/response/MyStatsMonthResponse.kt
  app/src/main/java/com/climus/climeet/data/remote/MainApi.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/RecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/RecordViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/CalendarFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/CalendarViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/DayViewContainer.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/ClimbingRecordCompleteFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/CreateClimbingRecordFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/calendar/createclimbingrecord/CreateClimbingRecordViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/model/CreateRecordData.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/stats/StatsFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/stats/StatsViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/stats/adapter/StatsGymAdapter.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/record/stats/datepicker/SelectYearMonthBottomSheet.kt
  app/src/main/java/com/climus/climeet/service/MyFirebaseMessagingService.kt
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_select_yearmonth_bottom_sheet.xml
  app/src/main/res/layout/fragment_stats.xml
  app/src/main/res/layout/item_stats_gym.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/navigation/main_nav.xml
Labels: feat

#51 [Profile/CMA-126] 암장 프로필 커뮤니티탭 구현 완료
  app/src/main/java/com/climus/climeet/data/model/response/GetGymSkillDistributionResponse.kt
  app/src/main/java/com/climus/climeet/data/model/response/GymWeekStatsResponse.kt
  app/src/main/java/com/climus/climeet/data/remote/MainApi.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepository.kt
  app/src/main/java/com/climus/climeet/data/repository/MainRepositoryImpl.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/bestclimber/detail/complete/GymProfileCompleteDetailViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/bestclimber/detail/time/GymProfileTimeDetailViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/completionrate/GymProfileAvgCompletionFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/completionrate/GymProfileAvgCompletionViewModel.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/skill/GymProfileSkillFragment.kt
  app/src/main/java/com/climus/climeet/presentation/ui/main/global/gymprofile/community/skill/GymProfileSkillViewModel.kt
  app/src/main/res/layout/fragment_gym_profile_avg_completion.xml
  app/src/main/res/layout/fragment_gym_profile_skill.xml
Labels: feat
